const locale=window.AiDiTiI18n;
let filter='All',limit=9,previousFocus,currentWork,printWork;
const gallery=document.querySelector('#gallery'),more=document.querySelector('#more'),dialog=document.querySelector('#viewer'),printDialog=document.querySelector('#print-request'),printForm=document.querySelector('#print-form');
const matches=w=>filter==='All'||(filter==='Moving'?['Video','Music Video','Mapping'].includes(w.category):filter==='Live'?['Live','Mapping'].includes(w.category):w.category===filter);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){const list=works.filter(matches);gallery.innerHTML=list.slice(0,limit).map(w=>`<button class="card ${w.category==='Drawing'?'drawing':''}" data-slug="${w.slug}" aria-label="${esc(locale.t('viewWork'))} ${esc(w.title)}"><div class="image"><img src="${w.image}" alt="${esc(w.title)}" loading="lazy"></div><div class="meta"><div><h3>${esc(w.title)}</h3><span class="cat">${esc(locale.category(w.category))}</span></div><span class="arrow">↗</span></div></button>`).join('');more.hidden=limit>=list.length;more.style.display=more.hidden?'none':'flex';}
function chooseFilter(next){filter=next;limit=9;document.querySelectorAll('[data-filter]').forEach(b=>{const active=b.dataset.filter===filter;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});render();}
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>chooseFilter(b.dataset.filter));more.onclick=()=>{limit+=9;render();};
document.querySelector('#browse-prints').onclick=()=>{chooseFilter('Drawing');document.querySelector('#work').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});document.querySelector('[data-filter="Drawing"]').focus({preventScroll:true});};
function translateDetail(){if(!currentWork||!dialog.open)return;locale.apply(document.querySelector('#detail'));document.querySelector('#detail .eyebrow').textContent=locale.category(currentWork.category);document.querySelector('#work-description').textContent=locale.description(currentWork);document.querySelector('#work-inquiry').href=`mailto:contact@aiditi.art?subject=${encodeURIComponent(locale.t('inquirySubject')+' '+currentWork.title)}`;document.querySelector('#detail iframe')?.setAttribute('title',locale.t('artworkVideo'));}
document.addEventListener('click',e=>{
 const play=e.target.closest('[data-play]');if(play){document.querySelector('#video-stage').innerHTML=`<iframe src="${play.dataset.play}${play.dataset.play.includes('?')?'&':'?'}autoplay=1" title="${esc(locale.t('artworkVideo'))}" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>`;return;}
 if(e.target.closest('[data-print]')){openPrint(currentWork);return;}
 const button=e.target.closest('[data-slug]');if(!button)return;const w=works.find(w=>w.slug===button.dataset.slug);if(!w)return;previousFocus=button;currentWork=w;
 const service=w.video?.includes('vimeo')?'Vimeo':'YouTube',videoLink=w.video?.includes('vimeo')?w.video.replace('player.vimeo.com/video/','vimeo.com/'):w.video?.replace('/embed/','/watch?v=');
 document.querySelector('#detail').innerHTML=`<span class="eyebrow">${esc(locale.category(w.category))}</span><div id="video-stage"><img src="${w.image}" alt="${esc(w.title)}">${w.video?`<button class="pill" data-play="${w.video}" data-i18n="play">${locale.t('play')}</button> <a class="text-link" href="${videoLink}" target="_blank" rel="noopener"><span data-i18n="watchOn">${locale.t('watchOn')}</span> ${service} ↗</a>`:''}</div><h2>${esc(w.title)}</h2><p id="work-description">${esc(locale.description(w))}</p><div class="artwork-actions">${w.category==='Drawing'?`<button class="pill print-cta" data-print="${w.slug}" data-i18n="requestPrint">${locale.t('requestPrint')}</button>`:''}<a id="work-inquiry" class="pill" data-i18n="askWork" href="mailto:contact@aiditi.art?subject=${encodeURIComponent(locale.t('inquirySubject')+' '+w.title)}">${locale.t('askWork')}</a></div>`;dialog.showModal();document.body.style.overflow='hidden';
});
function closeArtwork(){dialog.close();document.querySelector('#detail').innerHTML='';document.body.style.overflow='';if(previousFocus?.isConnected)previousFocus.focus({preventScroll:true});}
document.querySelector('#viewer .close').onclick=closeArtwork;dialog.addEventListener('cancel',e=>{e.preventDefault();closeArtwork();});dialog.addEventListener('click',e=>{if(e.target===dialog)closeArtwork();});
function openPrint(work){if(!work||work.category!=='Drawing')return;printWork=work;if(dialog.open)closeArtwork();printForm.reset();document.querySelector('#print-work').textContent=work.title;document.querySelector('#print-image').src=work.image;document.querySelector('#print-image').alt=work.title;printDialog.showModal();document.body.style.overflow='hidden';}
function closePrint(){printDialog.close();document.body.style.overflow='';if(previousFocus?.isConnected)previousFocus.focus({preventScroll:true});}
document.querySelector('#close-print').onclick=closePrint;printDialog.addEventListener('cancel',e=>{e.preventDefault();closePrint();});printDialog.addEventListener('click',e=>{if(e.target===printDialog)closePrint();});
printForm.addEventListener('submit',e=>{e.preventDefault();if(!printForm.reportValidity()||!printWork)return;const fields=new FormData(printForm),t=locale.t;const body=`${t('printGreeting')} “${printWork.title}”.\n\n${t('printNameField')}: ${fields.get('name')}\n${t('printEmailField')}: ${fields.get('email')}\n${t('printCountryField')}: ${fields.get('country')}\n${t('printQuantityField')}: ${fields.get('quantity')}\n${t('printSizeField')}: ${fields.get('size')||t('printRecommend')}\n\n${t('printThanks')}`;location.href=`mailto:contact@aiditi.art?subject=${encodeURIComponent(t('printSubject')+' '+printWork.title)}&body=${encodeURIComponent(body)}`;});
document.addEventListener('languagechange',()=>{render();translateDetail();document.querySelector('#viewer .close').setAttribute('aria-label',locale.t('closeArtwork'));});
document.querySelector('#viewer .close').setAttribute('aria-label',locale.t('closeArtwork'));render();
