window.AiDiTiDescriptions = {
  it: {
    'midnight': 'Uno dei videomapping realizzati durante il mio percorso artistico. Altri lavori sono disponibili sul mio canale YouTube, Ai Di Ti. Grazie per la visione.',
    '3d-light-painting-galaxy': 'Light painting in tempo reale: il segnale di una videocamera HD dal vivo diventa la texture di un oggetto 3D. Realizzato con Quartz Composer e Resolume Arena durante una giornata di prove e sperimentazioni. Cercavamo di creare una galassia piena di pianeti. Altri video esplorano questa tecnica nella serie 3D Light Painting. Light painting: Carlotta Bertelli. Video design: Angela Di Tomaso (Ai Di Ti). Musica: Massimiliano Cestari.',
    'tissot-the-power-of-light': 'POWER OF LIGHT. Breve video che documenta una performance dal vivo di light painting e videomapping per il lancio dell’orologio Tissot (SOLAR) T-TOUCH, al Museo della Scienza e della Tecnologia Leonardo da Vinci di Milano, il 25 settembre 2014. Una produzione The Lamplighter Project. Regia e performance: Carlotta Bertelli. Co-direzione artistica: Gianluca Guaitoli. Light painting: Liliana Iadeluca. Video design e video performance: Angela Di Tomaso. Sound design: Massimiliano Cestari. Tecnico: Johnny Papagni.',
    'reality-rem-riot-production': 'REALITY — Rem Riot Production. Cortometraggio d’animazione, 4 minuti e 30 secondi. Il film esplora la Singolarità tecnologica descritta da Vernor Vinge nel 1993: la possibilità di creare un’intelligenza superiore a quella umana, trasformando la civiltà e il ruolo dell’umanità. Direzione artistica, sceneggiatura, animazione e montaggio: Angela Di Tomaso (Ai Di Ti). Sceneggiatura e illustrazioni: Daniele Urgo. Fotografia: Serena D’Alessandro. Performer: Annalisa Pisoni. Musica: Awahoshi Kavan, «Creativeness», e Sardinia Bass Legalize, «Out Of Gravity». Il progetto comprende studi dei personaggi, del colore e dell’animazione. Tutti i diritti riservati.',
    'concerto-per-labirinto': '«Concerto per Labirinto» è un’installazione audiovisiva immersiva e una performance dal vivo. L’ambiente è un labirinto cubico con diversi livelli di texture, in cui il videomapping si frammenta e si propaga insieme a un sistema audio quadrifonico. Il progetto esplora le geometrie e le prospettive che emergono dalla percezione sensoriale: semplici linee si intrecciano in forme complesse, trasformando gradualmente lo spazio. Questo percorso evoca dispersione e smarrimento, come in un vero labirinto, mentre la musica guida verso l’uscita. L’installazione è stata presentata in diversi luoghi; la versione documentata nel video è stata creata per l’«Outside Showroom of Biennale di Venezia» del 2013, presso i Venice Docks. Musica: Massimiliano Cestari. Visual e concept: Ai Di Ti.',
    'lack-of-communication': 'In semiotica, un segno rappresenta qualcosa d’altro: è un’unità di significato che mette in relazione un segnale con il suo riferimento. Da questo concetto nasce un’installazione che esplora la comunicazione attraverso la LIS e un sistema di gesti, espressioni del volto e movimenti del corpo. Lack of Communication è un’installazione interattiva realizzata nel 2012 durante il laboratorio del Kernel Festival. Lo studio affronta i significati semiotici e simbolici della lingua dei segni. L’esperienza sensoriale cerca di abbattere alcune barriere incontrate da persone sorde, con difficoltà uditive o prive di comunicazione verbale. L’obiettivo era invertire i ruoli: il pubblico udente deve imitare i movimenti dei performer per ascoltare ciò che viene detto. Tra scienza e tecnologia si nascondono le risorse attuali del potenziale umano rivolto all’evoluzione.',
    'mi-module-01': 'No Human Subject. Breve video del 2013, girato a Milano. Il lavoro si confronta con le parole di Pier Paolo Pasolini del 1974 sulla difficoltà di riprendere la città nella sua completezza e sulla scelta di un’inquadratura che ne mostri la perfezione stilistica.',
    'breakfest-2019-stage-video-mapping': 'BreakFest 2019 — videomapping del palco principale. Progettazione della struttura: m0rf. Realizzazione: Spord e Z-Aires. Mapping dal vivo e visual: Ai Di Ti e m0rf. Luci: Burtik. Experimental Visual Performance: EXVIP.',
    'live-visual-laser-painting-demo': 'Demo di visual dal vivo e laser painting.',
    '3d-light-painting': 'Patch di light painting 3D creata con Quartz Composer. Altre informazioni sulla patch QC sono disponibili sul sito Kineme; altri video approfondiscono il light painting 3D in tempo reale.',
    'la-repubblica': 'L’installazione di questa grande R è stata realizzata per il progetto «La Repubblica delle Idee 2014». Il videomapping nasce dalla collaborazione con Adela Muntean. Luogo: Piccolo Teatro Grassi, Milano.',
    'innocenti': 'INNOCENTI — Dust in the City rappresenta un viaggio tra le particelle invisibili di amianto inalate dagli abitanti che occupano la fabbrica. Innocenti è uno stabilimento abbandonato e fortemente degradato alla periferia di Milano, a pochi metri da scuole e aree residenziali, che ospita una numerosa comunità rom. Il nome della fabbrica richiama il significato di «innocenti».',
    'mixed-media-01': 'Pittura digitale. Questa serie di dipinti digitali, realizzata con iPad, ritrae persone reali attraverso texture vivaci e tratti espressivi.',
    'draw-video-mapping': 'Videomapping sperimentale realizzato in meno di due ore. Il disegno è stato interamente improvvisato. Disegno e videomapping: Ai Di Ti. Musica: Ling Ling, «Acid Meltdown» (Acid Crush 01). Luogo: una piccola stanza a Londra.',
    'amycanbe-queens': 'Un viaggio intimo nella nostra vita: così familiare e così sconosciuto. «Queens» è tratto dall’album «Wolf». Brano scritto, arrangiato e interpretato da Amycanbe. Produzione: Mattia «Matta» Dallara e Amycanbe. Registrazione e mix: Mattia «Matta» Dallara, Deposito Zero Studios, Forlì. Mastering: Tommaso Bianchi, White Sound Mastering, Scandicci (FI). Regia del video: Ai Di Ti.',
    'diagnostik-burning-bridges': 'Primo singolo dell’EP «Every C is a K!». Musica: Tito Bettencourt. Regia del video: Ai Di Ti.'
  },
  fr: {
    'midnight': 'L’un des mappings vidéo réalisés au cours de mon parcours artistique. D’autres œuvres sont disponibles sur ma chaîne YouTube, Ai Di Ti. Merci de votre visite.',
    '3d-light-painting-galaxy': 'Light painting en temps réel : le flux d’une caméra HD en direct devient la texture d’un objet 3D. Créé avec Quartz Composer et Resolume Arena lors d’une journée d’essais et d’expérimentations. Nous cherchions à créer une galaxie remplie de planètes. D’autres vidéos explorent cette technique dans la série 3D Light Painting. Light painting : Carlotta Bertelli. Création vidéo : Angela Di Tomaso (Ai Di Ti). Musique : Massimiliano Cestari.',
    'tissot-the-power-of-light': 'POWER OF LIGHT. Ce court film documente une performance de light painting et de mapping vidéo pour le lancement de la montre Tissot (SOLAR) T-TOUCH, au Musée des sciences et des techniques Léonard-de-Vinci de Milan, le 25 septembre 2014. Une production The Lamplighter Project. Direction et performance : Carlotta Bertelli. Codirection artistique : Gianluca Guaitoli. Light painting : Liliana Iadeluca. Création et performance vidéo : Angela Di Tomaso. Création sonore : Massimiliano Cestari. Technique : Johnny Papagni.',
    'reality-rem-riot-production': 'REALITY — Rem Riot Production. Court métrage d’animation de 4 minutes 30. Le film explore la singularité technologique décrite par Vernor Vinge en 1993 : la possibilité de créer une intelligence supérieure à celle de l’être humain, transformant la civilisation et la place de l’humanité. Direction artistique, scénario, animation et montage : Angela Di Tomaso (Ai Di Ti). Scénario et illustrations : Daniele Urgo. Photographie : Serena D’Alessandro. Interprète : Annalisa Pisoni. Musique : Awahoshi Kavan, «Creativeness», et Sardinia Bass Legalize, «Out Of Gravity». Le projet comprend des études de personnages, de couleurs et d’animation. Tous droits réservés.',
    'concerto-per-labirinto': '«Concerto per Labirinto» est une installation audiovisuelle immersive et une performance en direct. Son environnement est un labyrinthe cubique composé de plusieurs niveaux de textures, où le mapping vidéo se fragmente et se propage avec un système sonore quadriphonique. Le projet explore les géométries et les perspectives qui se déploient à travers la perception sensorielle : des lignes simples s’entrelacent en motifs complexes et transforment progressivement l’espace. Ce parcours évoque la dispersion et la perte de repères, comme dans un véritable labyrinthe, tandis que la musique guide vers la sortie. Présentée dans différents lieux, l’installation documentée dans ce film a été créée pour l’«Outside Showroom of Biennale di Venezia» de 2013, aux Venice Docks. Musique : Massimiliano Cestari. Visuels et concept : Ai Di Ti.',
    'lack-of-communication': 'En sémiotique, un signe représente autre chose : c’est une unité de sens qui relie un signal à son référent. Cette idée a donné naissance à une installation explorant la communication par la LIS et un système de gestes, d’expressions du visage et de mouvements du corps. Lack of Communication est une installation interactive créée en 2012 lors du laboratoire du Kernel Festival. L’étude aborde les significations sémiotiques et symboliques de la langue des signes. Cette expérience sensorielle cherche à réduire certaines barrières rencontrées par les personnes sourdes, malentendantes ou privées de communication verbale. L’objectif était d’inverser les rôles : le public entendant doit imiter les mouvements des interprètes pour entendre ce qui est dit. Entre science et technologie se cachent les ressources actuelles du potentiel humain tourné vers l’évolution.',
    'mi-module-01': 'No Human Subject. Court film de 2013, tourné à Milan. L’œuvre dialogue avec les mots de Pier Paolo Pasolini en 1974 sur la difficulté de filmer une ville dans sa totalité et sur le choix d’un plan montrant sa perfection stylistique.',
    'breakfest-2019-stage-video-mapping': 'BreakFest 2019 — mapping vidéo de la scène principale. Conception de la structure : m0rf. Réalisation : Spord et Z-Aires. Mapping en direct et visuels : Ai Di Ti et m0rf. Lumières : Burtik. Experimental Visual Performance : EXVIP.',
    'live-visual-laser-painting-demo': 'Démonstration de visuels en direct et de laser painting.',
    '3d-light-painting': 'Patch de light painting 3D créé dans Quartz Composer. Le site Kineme propose des informations sur le patch QC ; d’autres vidéos explorent le light painting 3D en temps réel.',
    'la-repubblica': 'Cette installation d’un grand R a été réalisée pour le projet «La Repubblica delle Idee 2014». Le mapping vidéo est issu d’une collaboration avec Adela Muntean. Lieu : Piccolo Teatro Grassi, Milan.',
    'innocenti': 'INNOCENTI — Dust in the City représente un voyage parmi les particules invisibles d’amiante inhalées par les habitants qui occupent l’usine. Innocenti est une usine abandonnée et très dégradée à la périphérie de Milan, à quelques mètres d’écoles et de quartiers résidentiels, accueillant une importante communauté rom. Le nom de l’usine évoque le mot «innocents».',
    'mixed-media-01': 'Peinture numérique. Réalisée sur iPad, cette série de peintures numériques représente des personnes réelles à travers des textures vibrantes et des traits expressifs.',
    'draw-video-mapping': 'Mapping vidéo expérimental réalisé en moins de deux heures. Le dessin a été entièrement improvisé. Dessin et mapping vidéo : Ai Di Ti. Musique : Ling Ling, «Acid Meltdown» (Acid Crush 01). Lieu : une petite chambre à Londres.',
    'amycanbe-queens': 'Un voyage intime à travers notre vie : si familier et si inconnu. «Queens» est extrait de l’album «Wolf». Chanson écrite, arrangée et interprétée par Amycanbe. Production : Mattia «Matta» Dallara et Amycanbe. Enregistrement et mixage : Mattia «Matta» Dallara, Deposito Zero Studios, Forlì. Mastering : Tommaso Bianchi, White Sound Mastering, Scandicci (FI). Réalisation du clip : Ai Di Ti.',
    'diagnostik-burning-bridges': 'Premier single de l’EP «Every C is a K!». Musique : Tito Bettencourt. Réalisation du clip : Ai Di Ti.'
  }
};
